features:
  blacklist-entities: true
  blacklist-worlds: false
  stack-entity-with-customname: true # This maybe cause a problem with entities.

methods:
  radius-method: true
  chunk-method: false

radius-method:
  x: 20
  y: 10
  z: 20

# Performance for long term, disable if you have problems with entities
remove-entities-on-unload-chunk: true

# All entities: https://helpch.at/docs/1.8/index.html?org/bukkit/entity/EntityType.html
blacklist-entities:
  - "VILLAGER"

blacklist-worlds:
  - "world"