features:
  blacklist-entities: true
  blacklist-worlds: false

methods:
  radius-method: true
  chunk-method: false

radius-method:
  x: 20
  y: 10
  z: 20

#All entities: https://helpch.at/docs/1.8/index.html?org/bukkit/entity/EntityType.html
blacklist-entities:
  - "VILLAGER"

blacklist-worlds:
  - "world"