name: MobStacker
description: A basic mobstacker plugin
author: iChocoMC_
main: mobstacker.MobStacker
version: 8.1

commands:
  mobstacker:
    description: "Send all subcommands of /mobstacker | stats - reload - stack"