name: MobStacker
description: A basic mobstacker plugin
author: iChocoMC_
main: mobstacker.MobStacker
version: 5.0

commands:
  mobstacker:
    description: "Send all subcommands of /mobstacker - stats and reload"